### ISSUE TITLE
Default build requires JHU login

### ISSUE THREAD

**Issue by bill-baumgartner** [JHUAPL/PINE#16]
Hi, I've been able to successfully build and launch the project, however the default setup seems to require a JHU login in order to use the tool. Screenshot of the welcome screen attached. I'm wondering if I missed a configuration step somewhere.

System: `macOS Catalina 10.15.6`
Docker: `Docker version 19.03.13, build 4484c46d9d`; `docker-compose version 1.27.4, build 40524192`
Browser: `Google Chrome (Version 86.0.4240.198)`
Repo commit: 69312cf

Steps taken:
- `./pipelines/download_resources.sh`
- set `VEGAS_CLIENT_SECRET` in .env
- `export PINE_VERSION=$(./version.sh)`
- `docker-compose build`
- `docker-compose up`
- Navigated to `https://localhost:8888/`

![pine-welcome-screen](https://user-images.githubusercontent.com/7217210/99462008-12f15500-28f0-11eb-8a1f-761cd1826759.png)

**Comment by bwkchee** [comment]
It shouldn't be specific to JHEDs but we will need to change login language.  You can see users and/or add test data.  Please see the "User management using "eve" auth module" section on the front page/documentation.

**Comment by bill-baumgartner** [comment]
Thanks. I will give the `eve` module a try. You might considering invoking the `eve` module as the default since it doesn't require an external service. Also, the documentation could be augmented to more clearly discuss the differences between `vegas` and `eve` for users who may be unfamiliar with them.

The documentation should also indicate that a change to the [.env](https://github.com/JHUAPL/PINE/blob/master/.env) file is required to activate the `eve` auth module, i.e. `AUTH_MODULE=eve` Are there any other changes to the `.env` file or elsewhere required to activate the `eve` module?

**Comment by jhuapl-lglenden** [comment]
You're right that the top-level README.md needs to be updated to make the differences clear.  The information is scattered around various places and needs to be stated clearly in one place.  @bwkchee is also right that the eve auth module is the right way to go.  The only change you need is `AUTH_MODULE=eve` in the `.env` file.  It's also worth noting that the eve auth module uses users that are stored in the database, which starts off empty.  I see by the other issue #17 that you've started going down that path.  I'll be taking a look at that and also updating the README.md.

**Comment by jhuapl-lglenden** [comment]
README was updated with a quickstart and some more info in #19 .

**Comment by jhuapl-lglenden** [comment]
Default auth module is now eve.
